### ISSUE TITLE
brew formula needed

### ISSUE THREAD

**Issue by RichardBronosky** [benwebber/tunnelblickctl#6]
This really ought to be installed via `brew install tunnelblickctl`. Are you open to that?

**Comment by benwebber** [comment]
Yes, absolutely. Here's an example of a Rust formula:

https://github.com/Homebrew/homebrew-core/blob/46be226f7cf3ebf722b1c18a676fea3da403692a/Formula/hyperfine.rb

My time is a bit limited this week. If you'd like to submit the formula, please go ahead.

**Comment by benwebber** [comment]
I created a new tap! You can download the latest release like so:

```
brew tap benwebber/tunnelblickctl
brew install tunnelblickctl
```

I will submit the formula to homebrew-core if it attracts a larger user base (there are some notability standards to meet).
